#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output eDP-1-1 --primary --mode 1920x1080 --rotate normal --pos 1920x0 --output HDMI-0 --mode 1920x1080 --rotate normal --pos 0x0 --left-of eDP-1-1



#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1-1 -d 6 7 8 9 0
bspc monitor HDMI-0 -d 1 2 3 4 5


bspc config border_width         0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#resolucion arandr



# Wallpapers
feh --bg-fill ~/wallpapers/1.png


# Launch polybar
$HOME/.config/polybar/launch.sh


# PICOM
picom &
bspc config border_width 2


# Ver q hace esto.
#xsetroot -cursor_name left_ptr &
