#!/bin/bash


# ver algo como esto, para seleccionar los wallpapers a mano,
# ver si se puede automatizar en python y hacer un programita
# que controle los wallpapers.
# asd=$(ls -1 -d ~/images/wallpapers/* | sed -n 5p)

function set_wallpaper { feh --bg-fill $1; }

function check_walls_exists { python3 "$BSPWM"/check_walls_exists.py; }



# Setea un wallpaper aleatorio de entre los disponibles.
while [[ $# -gt 0 ]]; do
    case "$1" in
        --check-walls-exists) check_walls_exists;;
            #echo $(ls -d  ~/images/wallpapers/*);;
        -r) wallpaper=$(ls -d  ~/images/wallpapers/* | shuf -n 1);;
        -g) echo "asd";;
        -n) echo "set next wallpaper";;
        -p) echo "set prev wallpaper";;
        *) echo "Invalid flag"; exit 1;;
    esac
    shift
done


if [[ -f $wallpaper ]]; then
    set_wallpaper $wallpaper
fi

# Captura de pantallas
#scrot -q 100 -s "asd.png"; xclip -selection clipboard -t image/png -i 'asd.png'; rm "asd.png"