#!/bin/bash

function set_wallpaper { feh --bg-fill $1; }


# Setea un wallpaper aleatorio de entre los disponibles.
while [[ $# -gt 0 ]]; do
    case "$1" in
        -r) wall=$(ls -d  ~/images/wallpapers/* | shuf -n 1);;
        -g) echo "asd";;
        -n) echo "set next wallpaper";;
        -p) echo "set prev wallpaper";;
        *) echo "Invalid flag"; exit 1;;
    esac
    shift
done


if [[ -f $wall ]]; then
    set_wallpaper $wall
fi
