#!/bin/bash
# Comprueba si sxhkd está abierto como proceso,
# en caso de no estarlo lo inicia.
pgrep -x sxhkd > /dev/null || sxhkd &

#------------------------------------------------------------------------------
#  - Renderizado
#  TODO:
#   1. Poner condicionales para tener varios monitores conectados con
#   diferentes tamaños de monitor y que se acomode automaticamente.
#------------------------------------------------------------------------------
####################################################
#                  Monitor Setting                 #
####################################################
#---------------------------------------------------
#  - resolution
#---------------------------------------------------
xrandr --output eDP-1-1 --primary --mode 1920x1080 --rotate normal --pos 1920x0 \
    --output HDMI-0 --mode 1920x1080 --rotate normal --pos 0x0 --left-of eDP-1-1

#---------------------------------------------------
#  - monitors
#---------------------------------------------------
bspc monitor eDP-1-1 -d 6 7 8 9 0
bspc monitor HDMI-0 -d 1 2 3 4 5

####################################################
#                   Config BSPWM                   #
####################################################
#---------------------------------------------------
#  - color window
#---------------------------------------------------
bspc config focused_border_color \#3F87A7
bspc config active_border_color   \#1F4D62

#---------------------------------------------------
#  - window propertys
#---------------------------------------------------
bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Abrir spotify en tal ventana, mismo discord y whatsapp.
# Ver de como crear un monitor invisible, y que se pueda switchear entre monitores.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Wallpapers (Elige el primero aleatoriamente).
$HOME/.config/bspwm/wallpaper -r

# Launch polybar
$HOME/.config/polybar/launch.sh


# PICOM
picom --config $HOME/.config/picom/picom.conf &


# Ver q hace esto.
#xsetroot -cursor_name left_ptr &
