#!/bin/bash
# Comprueba si sxhkd está abierto como proceso,
# en caso de no estarlo lo inicia.
pgrep -x sxhkd > /dev/null || sxhkd &

# TODO: Poner condicional, si no está ya en latam, que lo ponga en latam, o lenguaje por defecto.
#setxkbmap -layout latam

wm_monitors


####################################################
#                   Config BSPWM                   #
####################################################
#---------------------------------------------------
#  - color window
#---------------------------------------------------
bspc config focused_border_color \#3F87A7
bspc config active_border_color   \#1F4D62

#---------------------------------------------------
#  - window propertys
#---------------------------------------------------
bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Abrir spotify en tal ventana, mismo discord y whatsapp.
# Ver de como crear un monitor invisible, y que se pueda switchear entre monitores.
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Wallpapers (Elige el primero aleatoriamente).
wm_wallpaper -r

# Launch polybar
$HOME/.config/polybar/launch.sh


# PICOM
picom --config $HOME/.config/picom/picom.conf &
#picom -b




# Ver q hace esto.
#xsetroot -cursor_name left_ptr &


#if [[ $(xdg-settings get default-web-browser) != brave-browser.desktop ]]; then
#    xdg-settings set default-web-browser brave-browser.desktop
#fi

